configuration:
  projectName: Admin UI
logging:
  level:
    org.springframework.security: DEBUG
security:
  user:
    role: USER,ADMIN
server:
  port: 8082
spring:
  redis:
    host: 192.168.1.11
---
spring:
  profiles: development
  redis:
    host: localhost
