configuration:
  projectName: Gateway
server:
  port: 80
logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
zuul:
  routes:
    ui:
      url: http://192.168.1.51:8081
    admin:
      url: http://192.168.1.51:8082
    resource:
      url: http://192.168.1.51:9000

spring:
  redis:
    host: 192.168.1.51
---
spring:
  profiles: development
  redis:
    host: localhost
server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
zuul:
  routes:
    ui:
      url: http://localhost:8081
    admin:
      url: http://localhost:8082
    resource:
      url: http://localhost:9000
