configuration:
  projectName: UI
server:
  port: 8081
logging:
  level:
    org.springframework.security: DEBUG
spring:
  redis:
    host: 192.168.1.11
---
spring:
  profiles: development
  redis:
    host: localhost
