server:
  port: 8080
configuration:
  projectName: UI
security:
  user:
    password: user
zuul:
 routes:
  resource:
    path: /resource/**
    url: http://localhost:9000/
    stripPrefix: false
  user:
    path: /user/**
    url: http://localhost:9999/uaa/user
    stripPrefix: false
spring:
  redis:
    host: 192.168.99.100