configuration:
  projectName: User service
server:
  port: 8002
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user-service

---

spring:
  profiles: development
server:
  port: 9002
